from sqlalchemy import (
    JSON,
    Column,
    DateTime,
    ForeignKey,
    Boolean,
    Integer,
    MetaData,
    Numeric,
    String,
    Table,
    Text,
    UniqueConstraint,
    text,
)

metadata = MetaData(schema="public")

users = Table(
    "users",
    metadata,
    Column("user_id", Integer, primary_key=True),
    Column("username", String(50), nullable=False, unique=True),
    Column("email", String(100), nullable=False, unique=True),
    Column("password_hash", String(255), nullable=False),
    Column("first_name", String(100), nullable=False),
    Column("last_name", String(100), nullable=False),
    Column("phone_number", String(15)),
    Column("role", String(20), nullable=False),
    Column("profile_picture_url", String(500)),
    Column("bio", Text),
    Column("city", String(100)),
    Column("zip_code", String(10)),
    Column("account_created_at", DateTime(timezone=True), server_default=text("NOW()")),
    Column("last_updated", DateTime(timezone=True), server_default=text("NOW()")),
    Column("is_active", Boolean, server_default=text("true")),
)

bands = Table(
    "bands",
    metadata,
    Column("band_id", Integer, primary_key=True),
    Column("band_name", String(150), nullable=False),
    Column("leader_id", Integer, ForeignKey("users.user_id"), nullable=False),
    Column("genre", String(100), nullable=False),
    Column("bio", Text),
    Column("profile_picture_url", String(500)),
    Column("member_count", Integer, server_default=text("1")),
    Column("city", String(100)),
    Column("zip_code", String(10)),
    Column("created_at", DateTime(timezone=True), server_default=text("NOW()")),
    Column("last_updated", DateTime(timezone=True), server_default=text("NOW()")),
    Column("is_active", Boolean, server_default=text("true")),
)

band_members = Table(
    "band_members",
    metadata,
    Column("member_id", Integer, primary_key=True),
    Column("band_id", Integer, ForeignKey("bands.band_id"), nullable=False),
    Column("user_id", Integer, ForeignKey("users.user_id"), nullable=False),
    Column("instrument", String(100), nullable=False),
    Column("role_in_band", String(50)),
    Column("joined_date", DateTime(timezone=True), server_default=text("NOW()")),
    UniqueConstraint("band_id", "user_id", name="uq_band_member"),
)

gig_listings = Table(
    "gig_listings",
    metadata,
    Column("gig_id", Integer, primary_key=True),
    Column("venue_owner_id", Integer, ForeignKey("users.user_id"), nullable=False),
    Column("gig_title", String(200), nullable=False),
    Column("description", Text),
    Column("genre_required", String(100), nullable=False),
    Column("performance_date", DateTime(timezone=True), nullable=False),
    Column("performance_time", String(10), nullable=False),
    Column("venue_name", String(150), nullable=False),
    Column("location_city", String(100), nullable=False),
    Column("location_zip_code", String(10)),
    Column("duration_hours", Numeric(3, 1)),
    Column("offered_pay", Numeric(10, 2), nullable=False),
    Column("payment_status", String(20), server_default=text("'Pending'")),
    Column("gig_status", String(20), server_default=text("'Open'")),
    Column("created_at", DateTime(timezone=True), server_default=text("NOW()")),
    Column("last_updated", DateTime(timezone=True), server_default=text("NOW()")),
)

applications = Table(
    "applications",
    metadata,
    Column("application_id", Integer, primary_key=True),
    Column("gig_id", Integer, ForeignKey("gig_listings.gig_id"), nullable=False),
    Column("band_id", Integer, ForeignKey("bands.band_id"), nullable=False),
    Column("application_date", DateTime(timezone=True), server_default=text("NOW()")),
    Column("application_status", String(20), server_default=text("'Pending'")),
    Column("cover_letter", Text),
    Column("last_updated", DateTime(timezone=True), server_default=text("NOW()")),
    UniqueConstraint("gig_id", "band_id", name="uq_application_once"),
)

bookings_contracts = Table(
    "bookings_contracts",
    metadata,
    Column("booking_id", Integer, primary_key=True),
    Column("gig_id", Integer, ForeignKey("gig_listings.gig_id"), nullable=False),
    Column("band_id", Integer, ForeignKey("bands.band_id"), nullable=False),
    Column("venue_owner_id", Integer, ForeignKey("users.user_id"), nullable=False),
    Column("contract_date", DateTime(timezone=True), server_default=text("NOW()")),
    Column("agreed_fee", Numeric(10, 2), nullable=False),
    Column("deposit_amount", Numeric(10, 2)),
    Column("deposit_status", String(20), server_default=text("'Pending'")),
    Column("contract_status", String(20), server_default=text("'Active'")),
    Column("performance_date", DateTime(timezone=True), nullable=False),
    Column("performance_time", String(10), nullable=False),
    Column("contract_terms", Text),
    Column("signed_at", DateTime(timezone=True), server_default=text("NOW()")),
    Column("completed_at", DateTime(timezone=True)),
)

availability_calendar = Table(
    "availability_calendar",
    metadata,
    Column("availability_id", Integer, primary_key=True),
    Column("user_id", Integer, ForeignKey("users.user_id"), nullable=False),
    Column("busy_date", DateTime(timezone=True), nullable=False),
    Column("busy_time_start", String(10)),
    Column("busy_time_end", String(10)),
    Column("reason", String(255)),
    Column("created_at", DateTime(timezone=True), server_default=text("NOW()")),
    UniqueConstraint("user_id", "busy_date", name="uq_user_date"),
)

payments = Table(
    "payments",
    metadata,
    Column("payment_id", Integer, primary_key=True),
    Column("booking_id", Integer, ForeignKey("bookings_contracts.booking_id"), nullable=False),
    Column("band_id", Integer, ForeignKey("bands.band_id"), nullable=False),
    Column("venue_owner_id", Integer, ForeignKey("users.user_id"), nullable=False),
    Column("amount", Numeric(10, 2), nullable=False),
    Column("payment_type", String(20), nullable=False),
    Column("payment_status", String(20), server_default=text("'Pending'")),
    Column("payment_date", DateTime(timezone=True)),
    Column("payment_method", String(50)),
    Column("transaction_id", String(100), unique=True),
    Column("notes", Text),
    Column("created_at", DateTime(timezone=True), server_default=text("NOW()")),
)

recruitment_ads = Table(
    "recruitment_ads",
    metadata,
    Column("recruitment_id", Integer, primary_key=True),
    Column("band_id", Integer, ForeignKey("bands.band_id"), nullable=False),
    Column("posted_by_user_id", Integer, ForeignKey("users.user_id"), nullable=False),
    Column("title", String(200), nullable=False),
    Column("description", Text),
    Column("instruments_needed", String(255), nullable=False),
    Column("genre", String(100), nullable=False),
    Column("experience_level", String(50)),
    Column("city", String(100)),
    Column("zip_code", String(10)),
    Column("ad_status", String(20), server_default=text("'Active'")),
    Column("created_at", DateTime(timezone=True), server_default=text("NOW()")),
    Column("last_updated", DateTime(timezone=True), server_default=text("NOW()")),
)

reviews_disputes = Table(
    "reviews_disputes",
    metadata,
    Column("review_id", Integer, primary_key=True),
    Column("booking_id", Integer, ForeignKey("bookings_contracts.booking_id"), nullable=False),
    Column("reviewer_id", Integer, ForeignKey("users.user_id")),
    Column("reviewee_id", Integer, ForeignKey("users.user_id")),
    Column("rating", Integer),
    Column("review_text", Text),
    Column("review_type", String(20), server_default=text("'Review'")),
    Column("dispute_reason", String(255)),
    Column("is_flagged", Boolean, server_default=text("false")),
    Column("admin_notes", Text),
    Column("status", String(20), server_default=text("'Open'")),
    Column("created_at", DateTime(timezone=True), server_default=text("NOW()")),
    Column("resolved_at", DateTime(timezone=True)),
)

setlists = Table(
    "setlists",
    metadata,
    Column("setlist_id", Integer, primary_key=True),
    Column("band_id", Integer, ForeignKey("bands.band_id"), nullable=False),
    Column("gig_id", Integer, ForeignKey("gig_listings.gig_id")),
    Column("setlist_name", String(200), nullable=False),
    Column("created_at", DateTime(timezone=True), server_default=text("NOW()")),
    Column("last_updated", DateTime(timezone=True), server_default=text("NOW()")),
)

setlist_songs = Table(
    "setlist_songs",
    metadata,
    Column("song_id", Integer, primary_key=True),
    Column("setlist_id", Integer, ForeignKey("setlists.setlist_id"), nullable=False),
    Column("song_title", String(200), nullable=False),
    Column("artist_name", String(150)),
    Column("duration_minutes", Numeric(4, 2)),
    Column("song_order", Integer, nullable=False),
    Column("genre", String(100)),
    Column("created_at", DateTime(timezone=True), server_default=text("NOW()")),
)
